/** Manually reviewed observations of the local user-supplied video, not engine constants.
 * 30 Hz frame intervals are [sourceStartFrame, sourceEndFrame). All nested frame
 * numbers are relative to sourceStartFrame. Raw keys persist until the next row.
 * Confidence describes HUD readability; quantitativeEligible separately describes
 * whether initial motion/boost state is identified sufficiently for a speed fit.
 */
export type ReferenceKey = 'up' | 'down' | 'left' | 'right' | 'drift' | 'boost';
export interface ReferenceClip {
  readonly id: string;
  readonly split: 'calibration' | 'validation';
  readonly skill: 'expert' | 'intermediate' | 'beginner';
  readonly family: string;
  readonly sourceStartFrame: number;
  readonly sourceEndFrame: number;
  readonly initialSpeedKmh: number;
  readonly initialBoostTicks: number;
  readonly initialStartTicks?: number;
  readonly initialBoosters?: number;
  readonly quantitativeEligible: boolean;
  readonly keys: readonly { readonly frame: number; readonly keys: readonly ReferenceKey[] }[];
  readonly observations: readonly { readonly frame: number; readonly speedKmh: number; readonly confidence: 'high' | 'medium'; readonly uncertaintyFrames: number }[];
  readonly events: readonly { readonly frame: number; readonly kind: string; readonly uncertaintyFrames: number; readonly notes: string }[];
  readonly notes: readonly string[];
}
export const REFERENCE_SOURCE = {
  sha256: 'af4ad63b07786412742068a0ff9c239f738730532cd7ced0acfdb241aa1e16a9',
  fps: 30, width: 1920, height: 1080, durationSeconds: 338.0351088435374,
  gameViewport: { x: 0, y: 0, width: 1440, height: 1080 },
} as const;

export const REFERENCE_CLIPS: readonly ReferenceClip[] = [
  {
    id: "expert-launch",
    split: "calibration",
    skill: "expert",
    family: "launch-and-opposite-drift",
    sourceStartFrame: 322,
    sourceEndFrame: 414,
    initialSpeedKmh: 0,
    initialBoostTicks: 0,
    initialStartTicks: 90,
    initialBoosters: 0,
    quantitativeEligible: true,
    keys: [
      {"frame": 0, "keys": ["up"]},
      {"frame": 2, "keys": ["up", "right"]},
      {"frame": 5, "keys": ["up", "left", "right"]},
      {"frame": 6, "keys": ["up", "left"]},
      {"frame": 12, "keys": ["up"]},
      {"frame": 20, "keys": ["up", "right"]},
      {"frame": 23, "keys": ["up"]},
      {"frame": 25, "keys": ["up", "right"]},
      {"frame": 32, "keys": ["up", "right", "drift"]},
      {"frame": 39, "keys": ["up"]},
      {"frame": 45, "keys": ["up", "left"]},
      {"frame": 49, "keys": ["left"]},
      {"frame": 51, "keys": ["left", "drift"]},
      {"frame": 55, "keys": ["up", "left", "drift"]},
      {"frame": 68, "keys": ["up", "left"]},
      {"frame": 71, "keys": ["up"]},
      {"frame": 74, "keys": ["up", "boost"]},
      {"frame": 75, "keys": ["up", "right"]},
      {"frame": 77, "keys": ["up", "right", "boost"]},
      {"frame": 80, "keys": ["up"]},
      {"frame": 83, "keys": ["up", "right"]},
      {"frame": 90, "keys": ["up"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 0, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 2, "speedKmh": 13, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 5, "speedKmh": 39, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 8, "speedKmh": 75, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 11, "speedKmh": 105, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 14, "speedKmh": 128, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 17, "speedKmh": 160, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 20, "speedKmh": 181, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 23, "speedKmh": 209, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 26, "speedKmh": 230, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 29, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 32, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 35, "speedKmh": 281, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 38, "speedKmh": 299, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 41, "speedKmh": 307, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 44, "speedKmh": 297, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 47, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 50, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 53, "speedKmh": 261, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 56, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 59, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 62, "speedKmh": 227, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 65, "speedKmh": 222, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 68, "speedKmh": 219, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 71, "speedKmh": 223, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 74, "speedKmh": 229, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 77, "speedKmh": 235, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 80, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 83, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 86, "speedKmh": 250, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 89, "speedKmh": 254, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 32, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 39, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 51, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 68, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "gauge-full-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 71, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 74, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 75, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 77, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 80, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Standing start has known zero velocity. Initial start boost is the existing 90-tick engineering hypothesis, not a measured timer; clip begins at the first raw throttle press and the pre-launch HUD shows zero.",
    ],
  },
  {
    id: "expert-right",
    split: "calibration",
    skill: "expert",
    family: "right-drift-and-countersteer",
    sourceStartFrame: 414,
    sourceEndFrame: 504,
    initialSpeedKmh: 259,
    initialBoostTicks: 138,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right"]},
      {"frame": 10, "keys": ["up", "right", "drift"]},
      {"frame": 15, "keys": ["up", "right"]},
      {"frame": 18, "keys": ["up"]},
      {"frame": 27, "keys": ["up", "left"]},
      {"frame": 33, "keys": ["up"]},
      {"frame": 37, "keys": ["up", "right"]},
      {"frame": 49, "keys": ["up"]},
      {"frame": 54, "keys": ["up", "left"]},
      {"frame": 57, "keys": ["up", "left", "drift"]},
      {"frame": 60, "keys": ["up", "left"]},
      {"frame": 62, "keys": ["up"]},
      {"frame": 65, "keys": ["up", "left"]},
      {"frame": 72, "keys": ["up", "left", "boost"]},
      {"frame": 73, "keys": ["up", "left"]},
      {"frame": 77, "keys": ["up", "left", "boost"]},
      {"frame": 82, "keys": ["up", "left"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 259, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 261, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 263, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 280, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 285, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 290, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 295, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 298, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 303, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 307, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 307, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 301, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 296, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 291, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 289, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 287, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 280, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 281, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 282, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 10, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 15, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 57, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 60, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 72, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 73, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 75, "kind": "gauge-full-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 77, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 77, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 82, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "expert-left",
    split: "calibration",
    skill: "expert",
    family: "left-drift-and-countersteer",
    sourceStartFrame: 504,
    sourceEndFrame: 594,
    initialSpeedKmh: 284,
    initialBoostTicks: 154,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "left"]},
      {"frame": 6, "keys": ["up"]},
      {"frame": 7, "keys": ["up", "left"]},
      {"frame": 8, "keys": ["up", "left", "drift"]},
      {"frame": 13, "keys": ["up", "left"]},
      {"frame": 14, "keys": ["up"]},
      {"frame": 22, "keys": ["up", "left"]},
      {"frame": 27, "keys": ["up"]},
      {"frame": 32, "keys": ["up", "right"]},
      {"frame": 45, "keys": ["up"]},
      {"frame": 46, "keys": ["up", "left"]},
      {"frame": 47, "keys": ["up", "left", "drift"]},
      {"frame": 51, "keys": ["up", "left"]},
      {"frame": 52, "keys": ["up"]},
      {"frame": 56, "keys": ["up", "right"]},
      {"frame": 60, "keys": ["up"]},
      {"frame": 63, "keys": ["up", "left"]},
      {"frame": 64, "keys": ["left"]},
      {"frame": 66, "keys": ["up", "left"]},
      {"frame": 69, "keys": ["up", "left", "boost"]},
      {"frame": 70, "keys": ["up"]},
      {"frame": 78, "keys": ["up", "left"]},
      {"frame": 81, "keys": ["up"]},
      {"frame": 85, "keys": ["up", "right"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 284, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 284, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 285, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 285, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 283, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 277, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 280, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 269, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 266, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 266, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 269, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 8, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 13, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 46, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 47, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 51, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 70, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "expert-repeat",
    split: "calibration",
    skill: "expert",
    family: "same-direction-repeat",
    sourceStartFrame: 594,
    sourceEndFrame: 714,
    initialSpeedKmh: 276,
    initialBoostTicks: 138,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right"]},
      {"frame": 2, "keys": ["up", "right", "drift"]},
      {"frame": 10, "keys": ["up", "drift"]},
      {"frame": 11, "keys": ["up"]},
      {"frame": 12, "keys": ["up", "right"]},
      {"frame": 21, "keys": ["up", "right", "drift"]},
      {"frame": 25, "keys": ["up", "right"]},
      {"frame": 27, "keys": ["up"]},
      {"frame": 32, "keys": ["up", "right"]},
      {"frame": 34, "keys": ["up"]},
      {"frame": 42, "keys": ["up", "left"]},
      {"frame": 57, "keys": ["up", "right", "drift"]},
      {"frame": 58, "keys": ["right", "drift"]},
      {"frame": 60, "keys": ["up", "right", "drift"]},
      {"frame": 62, "keys": ["up", "right"]},
      {"frame": 63, "keys": ["up"]},
      {"frame": 64, "keys": ["up", "right"]},
      {"frame": 70, "keys": ["up", "right", "boost"]},
      {"frame": 72, "keys": ["up"]},
      {"frame": 73, "keys": ["up", "boost"]},
      {"frame": 75, "keys": ["up"]},
      {"frame": 77, "keys": ["up", "boost"]},
      {"frame": 84, "keys": ["up"]},
      {"frame": 85, "keys": ["up", "left"]},
      {"frame": 95, "keys": ["up", "left", "drift"]},
      {"frame": 97, "keys": ["up", "left"]},
      {"frame": 98, "keys": ["up"]},
      {"frame": 109, "keys": ["up", "left"]},
      {"frame": 114, "keys": ["up"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 277, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 262, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 258, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 259, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 263, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 264, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 263, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 269, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 90, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 93, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 96, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 99, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 102, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 105, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 108, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 111, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 114, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 117, "speedKmh": 244, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 2, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 11, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 21, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 21, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 25, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 57, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 62, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 70, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 72, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 73, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 75, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 75, "kind": "booster-consumed-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 77, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 84, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 95, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 97, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "intermediate-launch",
    split: "validation",
    skill: "intermediate",
    family: "launch-and-opposite-drift",
    sourceStartFrame: 3441,
    sourceEndFrame: 3540,
    initialSpeedKmh: 0,
    initialBoostTicks: 0,
    initialStartTicks: 90,
    initialBoosters: 0,
    quantitativeEligible: true,
    keys: [
      {"frame": 0, "keys": ["up"]},
      {"frame": 2, "keys": ["up", "right"]},
      {"frame": 5, "keys": ["up", "left", "right"]},
      {"frame": 6, "keys": ["up", "left"]},
      {"frame": 12, "keys": ["up"]},
      {"frame": 20, "keys": ["up", "right"]},
      {"frame": 22, "keys": ["up"]},
      {"frame": 24, "keys": ["up", "right"]},
      {"frame": 32, "keys": ["up", "right", "drift"]},
      {"frame": 39, "keys": ["up", "right"]},
      {"frame": 40, "keys": ["up"]},
      {"frame": 45, "keys": ["up", "left"]},
      {"frame": 47, "keys": ["left"]},
      {"frame": 50, "keys": ["left", "drift"]},
      {"frame": 55, "keys": ["up", "left", "drift"]},
      {"frame": 68, "keys": ["up", "left"]},
      {"frame": 70, "keys": ["up"]},
      {"frame": 71, "keys": ["up", "boost"]},
      {"frame": 73, "keys": ["up"]},
      {"frame": 74, "keys": ["up", "right", "boost"]},
      {"frame": 77, "keys": ["up", "right"]},
      {"frame": 78, "keys": ["up", "right", "boost"]},
      {"frame": 80, "keys": ["up", "boost"]},
      {"frame": 81, "keys": ["up"]},
      {"frame": 83, "keys": ["up", "right"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 0, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 21, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 50, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 79, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 106, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 133, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 157, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 181, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 203, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 223, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 241, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 258, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 283, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 291, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 297, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 260, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 248, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 235, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 227, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 223, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 222, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 225, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 231, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 242, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 90, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 93, "speedKmh": 259, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 96, "speedKmh": 262, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 32, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 39, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 50, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 68, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "gauge-full-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 71, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 71, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 73, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 74, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 77, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 78, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 81, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Standing start has known zero velocity. Initial start boost is the existing 90-tick engineering hypothesis, not a measured timer; clip begins at the first raw throttle press and the pre-launch HUD shows zero.",
    ],
  },
  {
    id: "intermediate-right",
    split: "validation",
    skill: "intermediate",
    family: "right-drift-and-countersteer",
    sourceStartFrame: 3540,
    sourceEndFrame: 3630,
    initialSpeedKmh: 265,
    initialBoostTicks: 124,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right"]},
      {"frame": 3, "keys": ["up", "right", "drift"]},
      {"frame": 7, "keys": ["up", "right"]},
      {"frame": 9, "keys": ["up"]},
      {"frame": 14, "keys": ["up", "left"]},
      {"frame": 21, "keys": ["up"]},
      {"frame": 26, "keys": ["up", "right"]},
      {"frame": 35, "keys": ["up"]},
      {"frame": 46, "keys": ["up", "left"]},
      {"frame": 51, "keys": ["up", "left", "drift"]},
      {"frame": 54, "keys": ["up", "left"]},
      {"frame": 56, "keys": ["up"]},
      {"frame": 61, "keys": ["up", "left", "boost"]},
      {"frame": 62, "keys": ["up", "left"]},
      {"frame": 64, "keys": ["up", "left", "boost"]},
      {"frame": 65, "keys": ["up", "left"]},
      {"frame": 67, "keys": ["up", "left", "boost"]},
      {"frame": 73, "keys": ["up"]},
      {"frame": 75, "keys": ["up", "right"]},
      {"frame": 78, "keys": ["up"]},
      {"frame": 79, "keys": ["up", "left"]},
      {"frame": 82, "keys": ["up"]},
      {"frame": 86, "keys": ["up", "left"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 269, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 261, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 281, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 289, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 292, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 295, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 298, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 302, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 295, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 292, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 289, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 287, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 280, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 281, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 282, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 283, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 284, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 285, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 3, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 7, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 51, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 51, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 54, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 61, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 62, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 64, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 64, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 65, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 67, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 73, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "intermediate-left",
    split: "validation",
    skill: "intermediate",
    family: "left-drift-and-countersteer",
    sourceStartFrame: 3630,
    sourceEndFrame: 3720,
    initialSpeedKmh: 286,
    initialBoostTicks: 128,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "left"]},
      {"frame": 1, "keys": ["up", "left", "drift"]},
      {"frame": 7, "keys": ["up", "left"]},
      {"frame": 8, "keys": ["up"]},
      {"frame": 28, "keys": ["up", "left"]},
      {"frame": 30, "keys": ["up"]},
      {"frame": 36, "keys": ["up", "right"]},
      {"frame": 46, "keys": ["up", "left"]},
      {"frame": 48, "keys": ["up", "left", "drift"]},
      {"frame": 52, "keys": ["up", "left"]},
      {"frame": 53, "keys": ["up"]},
      {"frame": 57, "keys": ["up", "right"]},
      {"frame": 61, "keys": ["up"]},
      {"frame": 64, "keys": ["up", "boost"]},
      {"frame": 65, "keys": ["up"]},
      {"frame": 67, "keys": ["up", "boost"]},
      {"frame": 69, "keys": ["up"]},
      {"frame": 71, "keys": ["up", "boost"]},
      {"frame": 73, "keys": ["up", "left"]},
      {"frame": 77, "keys": ["up"]},
      {"frame": 83, "keys": ["up", "right"]},
      {"frame": 86, "keys": ["up", "right", "drift"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 284, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 279, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 280, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 281, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 282, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 283, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 286, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 291, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 1, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 7, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 48, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 51, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 52, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 64, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 64, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 65, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 67, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 71, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 73, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 86, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "intermediate-repeat",
    split: "validation",
    skill: "intermediate",
    family: "same-direction-repeat",
    sourceStartFrame: 3720,
    sourceEndFrame: 3810,
    initialSpeedKmh: 272,
    initialBoostTicks: 128,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right", "drift"]},
      {"frame": 5, "keys": ["up"]},
      {"frame": 11, "keys": ["up", "left"]},
      {"frame": 15, "keys": ["up"]},
      {"frame": 18, "keys": ["up", "right"]},
      {"frame": 19, "keys": ["up", "right", "drift"]},
      {"frame": 27, "keys": ["up", "right"]},
      {"frame": 28, "keys": ["up"]},
      {"frame": 36, "keys": ["up", "left"]},
      {"frame": 53, "keys": ["up", "left", "right"]},
      {"frame": 54, "keys": ["up", "right"]},
      {"frame": 56, "keys": ["up", "right", "drift"]},
      {"frame": 60, "keys": ["up", "right"]},
      {"frame": 62, "keys": ["up", "boost"]},
      {"frame": 64, "keys": ["up"]},
      {"frame": 65, "keys": ["up", "boost"]},
      {"frame": 67, "keys": ["up"]},
      {"frame": 69, "keys": ["up", "boost"]},
      {"frame": 71, "keys": ["up"]},
      {"frame": 72, "keys": ["up", "boost"]},
      {"frame": 75, "keys": ["up"]},
      {"frame": 78, "keys": ["up", "left"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 267, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 275, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 262, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 250, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 253, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 253, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 244, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 243, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 243, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 243, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 244, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 5, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 12, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 19, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 27, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 56, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 60, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 62, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 64, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 65, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 66, "kind": "booster-consumed-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 67, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 71, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 72, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 75, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
    ],
  },
  {
    id: "beginner-launch",
    split: "validation",
    skill: "beginner",
    family: "launch-and-opposite-drift",
    sourceStartFrame: 6727,
    sourceEndFrame: 6828,
    initialSpeedKmh: 0,
    initialBoostTicks: 0,
    initialStartTicks: 90,
    initialBoosters: 0,
    quantitativeEligible: true,
    keys: [
      {"frame": 0, "keys": ["up"]},
      {"frame": 11, "keys": ["up", "left"]},
      {"frame": 16, "keys": ["up"]},
      {"frame": 21, "keys": ["up", "right"]},
      {"frame": 26, "keys": ["up"]},
      {"frame": 31, "keys": ["up", "right"]},
      {"frame": 39, "keys": ["up", "right", "drift"]},
      {"frame": 47, "keys": ["up", "right"]},
      {"frame": 48, "keys": ["up"]},
      {"frame": 59, "keys": ["up", "left"]},
      {"frame": 60, "keys": ["up", "left", "drift"]},
      {"frame": 61, "keys": ["left", "drift"]},
      {"frame": 66, "keys": ["up", "left", "drift"]},
      {"frame": 80, "keys": ["up", "left"]},
      {"frame": 83, "keys": ["up", "boost"]},
      {"frame": 86, "keys": ["up"]},
      {"frame": 91, "keys": ["up", "right"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 0, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 2, "speedKmh": 18, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 5, "speedKmh": 47, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 8, "speedKmh": 75, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 11, "speedKmh": 103, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 14, "speedKmh": 129, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 17, "speedKmh": 155, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 20, "speedKmh": 178, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 23, "speedKmh": 200, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 26, "speedKmh": 220, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 29, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 32, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 35, "speedKmh": 271, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 38, "speedKmh": 285, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 41, "speedKmh": 301, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 44, "speedKmh": 317, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 47, "speedKmh": 309, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 50, "speedKmh": 295, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 53, "speedKmh": 284, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 56, "speedKmh": 273, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 59, "speedKmh": 261, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 62, "speedKmh": 250, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 65, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 68, "speedKmh": 222, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 71, "speedKmh": 210, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 74, "speedKmh": 203, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 77, "speedKmh": 201, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 80, "speedKmh": 201, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 83, "speedKmh": 204, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 86, "speedKmh": 211, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 89, "speedKmh": 217, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 92, "speedKmh": 223, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 95, "speedKmh": 228, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 98, "speedKmh": 234, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 39, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 47, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 60, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 80, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 80, "kind": "gauge-full-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 83, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 83, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 86, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "This run visibly uses a different kart body. Its unknown vehicle performance is a confound; compare its errors separately from expert/intermediate runs.",
      "Standing start has known zero velocity. Initial start boost is the existing 90-tick engineering hypothesis, not a measured timer; clip begins at the first raw throttle press and the pre-launch HUD shows zero.",
    ],
  },
  {
    id: "beginner-right",
    split: "validation",
    skill: "beginner",
    family: "right-drift-and-countersteer",
    sourceStartFrame: 6828,
    sourceEndFrame: 6924,
    initialSpeedKmh: 240,
    initialBoostTicks: 144,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right"]},
      {"frame": 8, "keys": ["up", "right", "drift"]},
      {"frame": 15, "keys": ["up", "right"]},
      {"frame": 16, "keys": ["up"]},
      {"frame": 26, "keys": ["up", "left"]},
      {"frame": 31, "keys": ["up"]},
      {"frame": 52, "keys": ["up", "drift"]},
      {"frame": 53, "keys": ["up", "left", "drift"]},
      {"frame": 57, "keys": ["up", "drift"]},
      {"frame": 58, "keys": ["up"]},
      {"frame": 66, "keys": ["up", "left"]},
      {"frame": 75, "keys": ["up"]},
      {"frame": 77, "keys": ["up", "boost"]},
      {"frame": 80, "keys": ["up"]},
      {"frame": 87, "keys": ["up", "left"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 240, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 253, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 254, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 254, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 248, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 250, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 253, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 259, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 262, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 90, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 93, "speedKmh": 268, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 8, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 15, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 52, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 58, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 71, "kind": "gauge-full-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 77, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 77, "kind": "booster-consumed-visible", "uncertaintyFrames": 1, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 80, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
      "This run visibly uses a different kart body. Its unknown vehicle performance is a confound; compare its errors separately from expert/intermediate runs.",
    ],
  },
  {
    id: "beginner-left",
    split: "validation",
    skill: "beginner",
    family: "left-drift-and-opposite-reentry",
    sourceStartFrame: 6924,
    sourceEndFrame: 7026,
    initialSpeedKmh: 270,
    initialBoostTicks: 142,
    initialStartTicks: 0,
    initialBoosters: 0,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "left"]},
      {"frame": 14, "keys": ["up", "left", "drift"]},
      {"frame": 20, "keys": ["up", "left"]},
      {"frame": 21, "keys": ["up"]},
      {"frame": 36, "keys": ["up", "right"]},
      {"frame": 38, "keys": ["up", "right", "drift"]},
      {"frame": 40, "keys": ["up", "drift"]},
      {"frame": 42, "keys": ["up"]},
      {"frame": 48, "keys": ["up", "right"]},
      {"frame": 61, "keys": ["up"]},
      {"frame": 63, "keys": ["up", "left"]},
      {"frame": 66, "keys": ["up", "left", "boost"]},
      {"frame": 68, "keys": ["up", "left"]},
      {"frame": 70, "keys": ["up", "left", "boost"]},
      {"frame": 73, "keys": ["up", "left"]},
      {"frame": 74, "keys": ["up", "left", "boost"]},
      {"frame": 77, "keys": ["up", "left"]},
      {"frame": 83, "keys": ["up", "left", "drift"]},
      {"frame": 92, "keys": ["up", "left"]},
      {"frame": 93, "keys": ["up"]},
      {"frame": 99, "keys": ["up", "right"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 272, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 274, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 277, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 278, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 276, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 270, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 269, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 265, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 261, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 257, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 251, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 246, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 248, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 247, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 242, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 238, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 240, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 244, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 243, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 245, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 252, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 255, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 258, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 260, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 90, "speedKmh": 258, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 93, "speedKmh": 256, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 96, "speedKmh": 254, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 99, "speedKmh": 249, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 14, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 20, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 38, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 42, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 57, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 66, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 68, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 70, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 72, "kind": "booster-consumed-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 73, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 74, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 77, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 83, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 92, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "Initial normal-boost remaining time is an explicit inference from observed inventory consumption and a provisional 180-tick duration; not an observed original-engine timer. Excluded from quantitative acceptance.",
      "This run visibly uses a different kart body. Its unknown vehicle performance is a confound; compare its errors separately from expert/intermediate runs.",
    ],
  },
  {
    id: "beginner-repeat",
    split: "validation",
    skill: "beginner",
    family: "same-direction-repeat-and-rise",
    sourceStartFrame: 7104,
    sourceEndFrame: 7230,
    initialSpeedKmh: 214,
    initialBoostTicks: 0,
    initialStartTicks: 0,
    initialBoosters: 1,
    quantitativeEligible: false,
    keys: [
      {"frame": 0, "keys": ["up", "right"]},
      {"frame": 6, "keys": ["up", "right", "drift"]},
      {"frame": 14, "keys": ["up", "right"]},
      {"frame": 15, "keys": ["up"]},
      {"frame": 24, "keys": ["up", "left"]},
      {"frame": 29, "keys": ["up"]},
      {"frame": 35, "keys": ["up", "left", "drift"]},
      {"frame": 45, "keys": ["up"]},
      {"frame": 52, "keys": ["up", "right"]},
      {"frame": 69, "keys": ["up", "right", "boost"]},
      {"frame": 70, "keys": ["up", "boost"]},
      {"frame": 71, "keys": ["up"]},
      {"frame": 72, "keys": ["up", "boost"]},
      {"frame": 79, "keys": ["up", "left", "boost"]},
      {"frame": 80, "keys": ["up", "left"]},
      {"frame": 82, "keys": ["up", "left", "drift"]},
      {"frame": 88, "keys": ["up"]},
      {"frame": 113, "keys": ["up", "left"]},
      {"frame": 115, "keys": ["up", "left", "drift"]},
      {"frame": 123, "keys": ["up"]},
    ],
    observations: [
      {"frame": 0, "speedKmh": 214, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 3, "speedKmh": 217, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 6, "speedKmh": 221, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 9, "speedKmh": 226, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 12, "speedKmh": 229, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 15, "speedKmh": 229, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 18, "speedKmh": 231, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 21, "speedKmh": 230, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 24, "speedKmh": 227, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 27, "speedKmh": 223, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 30, "speedKmh": 219, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 33, "speedKmh": 218, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 36, "speedKmh": 219, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 39, "speedKmh": 219, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 42, "speedKmh": 219, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 45, "speedKmh": 221, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 48, "speedKmh": 225, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 51, "speedKmh": 232, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 54, "speedKmh": 231, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 57, "speedKmh": 235, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 60, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 63, "speedKmh": 239, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 66, "speedKmh": 238, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 69, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 72, "speedKmh": 236, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 75, "speedKmh": 236, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 78, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 81, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 84, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 87, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 90, "speedKmh": 237, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 93, "speedKmh": 234, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 96, "speedKmh": 231, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 99, "speedKmh": 229, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 102, "speedKmh": 230, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 105, "speedKmh": 232, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 108, "speedKmh": 225, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 111, "speedKmh": 224, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 114, "speedKmh": 221, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 117, "speedKmh": 222, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 120, "speedKmh": 225, "confidence": "high", "uncertaintyFrames": 1},
      {"frame": 123, "speedKmh": 225, "confidence": "high", "uncertaintyFrames": 1},
    ],
    events: [
      {"frame": 6, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 14, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 35, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 45, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 69, "kind": "booster-consumed-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 71, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 72, "kind": "input-boost-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 80, "kind": "input-boost-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 82, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 88, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 114, "kind": "gauge-full-visible", "uncertaintyFrames": 3, "notes": "Inventory HUD icon appears or disappears in the source pixels; this is not an inferred internal gauge value or duration."},
      {"frame": 115, "kind": "input-drift-press", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
      {"frame": 123, "kind": "input-drift-release", "uncertaintyFrames": 1, "notes": "Observed key-overlay transition; overlay-to-engine latency is unknown."},
    ],
    notes: [
      "The key overlay can lag game events by up to three source frames (100 ms): the first expert booster icon disappears at frame393 before Ctrl lights at396. Raw keys are not shifted.",
      "Key transitions sampled every source frame; HUD OCR every three frames with visual spot checks.",
      "Source camera and course differ from the fixed comparison course; heading and sideslip are not recoverable from this video.",
      "This run visibly uses a different kart body. Its unknown vehicle performance is a confound; compare its errors separately from expert/intermediate runs.",
      "Initial drift/boost history and uphill section confound absolute speed; this clip tests input continuity and rendering only.",
    ],
  },
];
